### ISSUE TITLE
Lines disappear in editor

### ISSUE THREAD

**Issue by gaekwad** [orlof/dcpu-admiral#20]
I noticed this on the TC test server.  Lines in the editor that start with a space disappear when you hit enter to go to the next line.

**Comment by orlof** [comment]
Fixed in 0.92.

This issue was introduced in the newly optimized editor refresh routine. if line starts with spaces, editor adds same amount of spaces to the beginning of the next line. Newline character flagged the screen_dirty, but adding the spaces before screen refresh overwrote the screen_dirty with line_dirty - thus disabling the screen refresh.
